### ISSUE TITLE
PjSipService(14150)

### ISSUE THREAD

**Issue by real1988** [datso/react-native-pjsip#68]
Who can help me see this? I'm going to crumble！！！
I used react-native-pjsip to write a small case，And that's the way it turns out. why  why why

02-07 20:16:20.526: E/memtrack(14106): Couldn't load memtrack module (No such file or directory)
02-07 20:16:20.526: E/android.os.Debug(14106): failed to load memtrack module: -2
02-07 20:16:23.066: E/memtrack(14119): Couldn't load memtrack module (No such file or directory)
02-07 20:16:23.066: E/android.os.Debug(14119): failed to load memtrack module: -2
02-07 20:16:24.956: E/memtrack(14140): Couldn't load memtrack module (No such file or directory)
02-07 20:16:24.956: E/android.os.Debug(14140): failed to load memtrack module: -2
02-07 20:16:26.626: E/dalvikvm(14150): dlopen("/data/app-lib/com.pjsip-2/libpjsua2.so") failed: dlopen failed: cannot locate symbol "rand" referenced by "libpjsua2.so"...
02-07 20:16:26.626: E/PjSipService(14150): Error while loading PJSIP pjsua2 native library
02-07 20:16:26.626: E/PjSipService(14150): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "rand" referenced by "libpjsua2.so"...
02-07 20:16:26.626: E/PjSipService(14150): 	at java.lang.Runtime.loadLibrary(Runtime.java:364)
02-07 20:16:26.626: E/PjSipService(14150): 	at java.lang.System.loadLibrary(System.java:526)
02-07 20:16:26.626: E/PjSipService(14150): 	at com.carusto.ReactNativePjSip.PjSipService.load(PjSipService.java:129)
02-07 20:16:26.626: E/PjSipService(14150): 	at com.carusto.ReactNativePjSip.PjSipService.access$100(PjSipService.java:52)
02-07 20:16:26.626: E/PjSipService(14150): 	at com.carusto.ReactNativePjSip.PjSipService$2.run(PjSipService.java:235)
02-07 20:16:26.626: E/PjSipService(14150): 	at android.os.Handler.handleCallback(Handler.java:733)
02-07 20:16:26.626: E/PjSipService(14150): 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-07 20:16:26.626: E/PjSipService(14150): 	at android.os.Looper.loop(Looper.java:136)
02-07 20:16:26.626: E/PjSipService(14150): 	at android.os.HandlerThread.run(HandlerThread.java:61)
02-07 20:16:26.626: E/AndroidRuntime(14150): FATAL EXCEPTION: PjSipService
02-07 20:16:26.626: E/AndroidRuntime(14150): Process: com.pjsip, PID: 14150
02-07 20:16:26.626: E/AndroidRuntime(14150): java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "rand" referenced by "libpjsua2.so"...
02-07 20:16:26.626: E/AndroidRuntime(14150): 	at com.carusto.ReactNativePjSip.PjSipService.load(PjSipService.java:132)
02-07 20:16:26.626: E/AndroidRuntime(14150): 	at com.carusto.ReactNativePjSip.PjSipService.access$100(PjSipService.java:52)
02-07 20:16:26.626: E/AndroidRuntime(14150): 	at com.carusto.ReactNativePjSip.PjSipService$2.run(PjSipService.java:235)
02-07 20:16:26.626: E/AndroidRuntime(14150): 	at android.os.Handler.handleCallback(Handler.java:733)
02-07 20:16:26.626: E/AndroidRuntime(14150): 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-07 20:16:26.626: E/AndroidRuntime(14150): 	at android.os.Looper.loop(Looper.java:136)
02-07 20:16:26.626: E/AndroidRuntime(14150): 	at android.os.HandlerThread.run(HandlerThread.java:61)
02-07 20:16:26.626: E/AndroidRuntime(14150): Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "rand" referenced by "libpjsua2.so"...
02-07 20:16:26.626: E/AndroidRuntime(14150): 	at java.lang.Runtime.loadLibrary(Runtime.java:364)
02-07 20:16:26.626: E/AndroidRuntime(14150): 	at java.lang.System.loadLibrary(System.java:526)
02-07 20:16:26.626: E/AndroidRuntime(14150): 	at com.carusto.ReactNativePjSip.PjSipService.load(PjSipService.java:129)
02-07 20:16:26.626: E/AndroidRuntime(14150): 	... 6 more
02-07 20:21:50.222: E/BandwidthController(168): Updating quota globalAlert failed (No such file or directory)

**Comment by datso** [comment]
The problem is in:
```
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "rand" referenced by "libpjsua2.so"...
```

What is the device and android version ?

**Comment by lavarajallu** [comment]
Hi dasto, where can i place this  line or how to give my code

**Comment by tuledev** [comment]
I meet this problem on Android 4.x
