### ISSUE TITLE
Getting this error in android

### ISSUE THREAD

**Issue by lavarajallu** [datso/react-native-pjsip#75]
Loading dependency graph, done.
Error
    at DependencyGraph._getAbsolutePath (/Users/stellent/Desktop/react-native-pjsip-app/node_modules/react-native/packager/react-packager/src/node-haste/index.js:346:11)
    at load.then (/Users/stellent/Desktop/react-native-pjsip-app/node_modules/react-native/packager/react-packager/src/node-haste/index.js:289:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:1339) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): NotFoundError: Cannot find entry file index.delta.js in any of the roots: ["/Users/stellent/Desktop/react-native-pjsip-app"]
(node:1339) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Bundling `index.ios.js`
  Transforming modules  100.0% (564/564), done.
Error
    at DependencyGraph._getAbsolutePath (/Users/stellent/Desktop/react-native-pjsip-app/node_modules/react-native/packager/react-packager/src/node-haste/index.js:346:11)
    at load.then (/Users/stellent/Desktop/react-native-pjsip-app/node_modules/react-native/packager/react-packager/src/node-haste/index.js:289:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
::ffff:127.0.0.1 - - [23/Feb/2018:16:04:44 +0000] "GET /index.delta?platform=android&dev=true&minify=false&deltaBundleId=0 HTTP/1.1" 404 91 "-" "okhttp/3.6.0"

**Comment by datso** [comment]
Hi, please re-open the ticket with well formatted description and the error.
