### ISSUE TITLE
java.lang.RuntimeException: Unable to instantiate receiver com.carusto.ReactNativePjSip.PjSipConnectivityReceiver

### ISSUE THREAD

**Issue by rcorrie** [datso/react-native-pjsip#89]
App will sometimes crash randomly with this error:

```
Package: com.idt.unite
Version Code: 10
Version Name: 1.0.10
Android: 8.1.0
Android Build: OPM1.171019.021
Manufacturer: Google
Model: Pixel 2 XL
Thread: main-2
CrashReporter Key: DE5C7320-BFD0-0E6A-C7DC-E1E940CB677B2B20B639
Start Date: Thu Mar 29 10:42:46 EDT 2018
Date: Thu Mar 29 11:03:08 EDT 2018

java.lang.RuntimeException: Unable to instantiate receiver com.carusto.ReactNativePjSip.PjSipConnectivityReceiver: java.lang.ClassNotFoundException: Didn't find class "com.carusto.ReactNativePjSip.PjSipConnectivityReceiver" on path: DexPathList[[zip file "/data/app/com.idt.unite-kYjs4SWhWjB_8dXWC-pybw==/base.apk"],nativeLibraryDirectories=[/data/app/com.idt.unite-kYjs4SWhWjB_8dXWC-pybw==/lib/arm, /system/fake-libs, /data/app/com.idt.unite-kYjs4SWhWjB_8dXWC-pybw==/base.apk!/lib/armeabi-v7a, /system/lib]]
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3171)
	at android.app.ActivityThread.-wrap17(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.carusto.ReactNativePjSip.PjSipConnectivityReceiver" on path: DexPathList[[zip file "/data/app/com.idt.unite-kYjs4SWhWjB_8dXWC-pybw==/base.apk"],nativeLibraryDirectories=[/data/app/com.idt.unite-kYjs4SWhWjB_8dXWC-pybw==/lib/arm, /system/fake-libs, /data/app/com.idt.unite-kYjs4SWhWjB_8dXWC-pybw==/base.apk!/lib/armeabi-v7a, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3166)
	... 8 more
```

**Comment by datso** [comment]
Hey, just remove it from the Android manifest

**Comment by rcorrie** [comment]
Thanks

**Comment by mason-chase** [comment]
Hi There,

May I know How does the PJSip would know when network status changes without `PjSipConnectivityReceiver` ?

Regards
